feat: Menu option to Invert F Keys
pop-os/keyboard-configurator pull request #116
Opened 2021-12-21 22:05 UTC by ids1024

Implements https://github.com/pop-os/keyboard-configurator/issues/24.

Not sure if there's a better way to describe this, or any other way to improve it, but it seems appropriate to provide an easy way to do this. It is a common option provided by laptop firmware these days, and users have complained that it's overly complicated to change each key manually.

This has no impact on the default Launch layout since nothing is bound on layer 2 for the F keys. Not sure if that could be confusing or could be improved.

2021-12-22 18:15 UTC, 13r0ck requested changes
The button still appears when the launch keyboard is being configured. The button should either work for the launch, or shouldn't show

I think it would also be nice to have some sort of notification when first clicking an `f` key, to tell the user that that button exists. The location wasn't immediately obvious to me. That is personal preference and not blocking though.

2021-12-22 23:47 UTC, ids1024 commented
> The button should either work for the launch, or shouldn't show

Technically it does work for the Launch, but has no effect with the default layout. In principle it could be useful if someone is using a custom layout that binds functions to fn+f keys. I wonder if it would be best to make the button insensitive when it would have no effect, rather than removing it for Launch.

> I think it would also be nice to have some sort of notification when first clicking an f key

Great point. I'm sure there's some room for improvement, but I don't know what the best design would be.

2021-12-27 21:18 UTC, ids1024 commented
Amended to make the menu item insensitive for Launch (rather than hidden just since that's have GTK handles actions that are "disabled").

Could be improved more, but this should be better than not having an option for this.

2021-12-27 23:32 UTC, 13r0ck approved these changes
Agreed, this still leaves a lot to be desired, but this is an improvement none the less.

2022-01-03 16:39 UTC, jackpot51 approved these changes

2022-01-03 16:39 UTC, merged