fix: Use usage page and id to detect launch keyboard, not interface number
pop-os/keyboard-configurator pull request #171
Opened 2023-04-06 22:18 UTC by ids1024

For some reason, on macOS 13.3, hidapi is returning `0` as the interface number for everything. Using the usage page and id should work correctly across platforms.

Tested on macOS 13.3 and Pop!_OS. Still need to try Windows.

Fixes https://github.com/pop-os/keyboard-configurator/issues/168.

2023-04-11 18:23 UTC, ids1024 commented
When https://github.com/pop-os/keyboard-configurator/pull/173 is merged this can be rebased and have passing CI. Then we'll have build artifacts to test.

2023-04-12 16:24 UTC, ids1024 commented
Rebasing on https://github.com/pop-os/keyboard-configurator/pull/173 to get the CI to pass, Windows .msi artifact looks good too.

2023-04-14 20:34 UTC, leviport requested changes
This fixes detection on macOS 13, but the AppImage is no longer detecting Launch keyboards. It detects the built-in keyboard on my Oryx, but none of my Launches.

2023-04-19 16:44 UTC, ids1024 commented
Updated to use the old method of detection, except on macOS. Seems to work as expected on Pop!_OS and macOS 13.3.

2023-04-24 22:28 UTC, leviport commented
The .dmg is still working on macOS 13

2023-04-24 22:32 UTC, n3m0-22 approved these changes
Tested and working on Pop and Win10
 - [x] installed from the PR
 - [x] appimage
 - [x] msi

2023-05-01 22:45 UTC, 13r0ck approved these changes
My only concern with this would be that it might make longer to refresh, and cause issues with nelson. But on linux it is just 2 extra if statements, so I highly doubt it.

2023-05-01 22:52 UTC, merged